#!/bin/bash

## Select DVB channel and
## show with mplayer

## load some values
chan_file=~/.mplayer/channels.conf
butlabel=""
a=0
sel_chan="OOPS"

## set it up so there are the right num buttons
##  and they have the right label
while IFS=':' read -r channel line; do
    [ "$a" -lt "1" ] && butlabel="$channel:$channel" || \
        butlabel="$butlabel,$channel:$channel"
	((a++))
	# printf "BUTLABEL == %s\n" $butlabel
done < "$chan_file"
IFS=

sel_chan=`xmessage -center -print -buttons $butlabel "Select Channel"`
# printf "Selected Channel $sel_chan\n"
exec mplayer dvb://"$sel_chan" -demuxer mpegts

exit 0
